"""add migration

Revision ID: 033f4c971375
Revises: 
Create Date: 2025-05-27 13:49:33.114021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033f4c971375'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_model', sa.Column('location', sa.String(), nullable=True))
    op.create_index(op.f('ix_test_model_location'), 'test_model', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_model_location'), table_name='test_model')
    op.drop_column('test_model', 'location')
    # ### end Alembic commands ###
